### ISSUE TITLE
Upload Design

### ISSUE THREAD

**Issue by larsbirger** [G9-Robotikk-2023-hvl/Tidybot#4]

**Comment by larsbirger** [comment]
@MikkelSundberg  can you fix 3d file in STL or STEP or OBJ or IGES?

**Comment by larsbirger** [comment]
sånn bare send delelink elns fra drive eller dropbox elns evt direkte del fra tinkercad

**Comment by MikkelSundberg** [comment]
[tidywork.zip](https://github.com/G9-Robotikk-2023-hvl/Tidybot/files/13238679/tidywork.zip)

**Comment by MikkelSundberg** [comment]
håpe denne funke

**Comment by larsbirger** [comment]
# rotated file

- [tidywork.zip](https://github.com/G9-Robotikk-2023-hvl/Tidybot/files/13259448/tidywork.zip)

**Comment by MikkelSundberg** [comment]
[BetterWorksHalfSize.zip](https://github.com/G9-Robotikk-2023-hvl/Tidybot/files/13588896/BetterWorksHalfSize.zip)
